In [17]:
n = input()

ls = [1] * (len(n) + 1)

if len(n) == 0: print(0)
else: ls[1] = 1
    
for i in range(1, len(ls)-1):
    if 10 < int(n[i-1:i+1])<=26:
        ls[i+1] = ls[i] + ls[i-1]
    else:        

        ls[i+1] = ls[i]

        
print(ls)

123
[1, 1, 2, 3]


In [166]:

a = [[[1,2],[1,2]],[[1,2],[1,2]]]

sum(a[0][:][1])

3

In [124]:
import numpy as np

m,n=map(int,input().split())

img_ls = [[1]*n for i in range(m)]
for i in range(m):
    img_ls[i][:] = map(int,input().split())
    

KeyboardInterrupt: 

In [125]:
img_ls = [[1, 0, 0, 1, 0, 0],
 [0, 0, 1, 0, 1, 0],
 [1, 1, 1, 1, 1, 0],
 [1, 0, 0, 1, 1, 1],
 [1, 1, 1, 1, 1, 1]]

img_ls

[[1, 0, 0, 1, 0, 0],
 [0, 0, 1, 0, 1, 0],
 [1, 1, 1, 1, 1, 0],
 [1, 0, 0, 1, 1, 1],
 [1, 1, 1, 1, 1, 1]]

In [126]:
# up to down, left to right 
for i in range(1,m-1):
    for j in range(1, n-1):
        if img_ls[i][j] == 0:
            if img_ls[i][j-1] + img_ls[i-1][j] > 1:
                img_ls[i][j] = 0.6

In [127]:
img_ls

[[1, 0, 0, 1, 0, 0],
 [0, 0, 1, 0.6, 1, 0],
 [1, 1, 1, 1, 1, 0],
 [1, 0.6, 0.6, 1, 1, 1],
 [1, 1, 1, 1, 1, 1]]

In [128]:
# down to up and right to left
for i in range(m-2, 0, -1):
    for j in range(n-2, 0, -1):
        if img_ls[i][j] == 0.6:
            if img_ls[i][j+1] + img_ls[i+1][j] == 2:
                img_ls[i][j] = 1
            else: img_ls[i][j] = 0
                
img_ls

[[1, 0, 0, 1, 0, 0],
 [0, 0, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1]]

In [131]:
# padding zeros
for i in range(m):
    img_ls[i] = [0] + img_ls[i] + [0]
    
img_ls

[[0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]]

In [106]:

padding_img = np.hstack((np.array([[0] for i in range(m)]),img))
padding_img = np.hstack((padding_img, np.array([[0] for i in range(m)])))

padding_img


array([[0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0]])

In [133]:
# 找出相连陆地面积，把不相连的陆地像素设为0
padding_img = img_ls
for i in range(m-2,-1,-1):
    for j in range(1,n+1):
        if padding_img[i][j] == 1 and sum(padding_img[i+1][j-1:j+2])==0:
            padding_img[i][j] = 0


0 2


In [140]:
sum([sum(padding_img[i]) for i in range(m)])

21

In [197]:
# number of k
k = 2

ls = [[i+1, i-1] for i in range(10000)]

for i in range(5000):
    ls[i] = [0, 0] 
for i in range(5000,10000):
    ls[i] = [2, 2] 
center_point = [ls[i] for i in range(k)]
distance = [1 for i in range(k)]
cluster_point = [[] for i in range(k)]



while(1):
    
    # cluseter
    cluster_point = [[] for i in range(k)]
    new_distance = [0 for i in range(k)]
    
    for point in ls:
        dis = []
        for i in range(k):
            dis.append(abs(point[0] - center_point[i][0]) + abs(point[1] - center_point[i][1]))
        cluster_point[dis.index(min(dis))].append(point)
        # calculate new distance 
        new_distance[dis.index(min(dis))] += min(dis)
    
    if new_distance == distance: 
        break
    else: distance = new_distance 
    
    # get new center point
    for i in range(k):
#         print(i, cluster_point[i])
        if len(cluster_point[i])>0:
            x = sum([a[0] for a in cluster_point[i]])/len(cluster_point[i])
            y = sum([a[1] for a in cluster_point[i]])/len(cluster_point[i])
        else: x, y = 0, 0
        center_point[i] = [x,y]
# output
for i in center_point: print(i[0], i[1])

2.0 2.0
0.0 0.0


In [187]:
a = [[1, -1],[2, 1]]

sum([i[0] for i in a])

3

链接：https://www.nowcoder.com/questionTerminal/0399d363fb594970bae7ad8a3978f86a?orderByHotValue=1&page=1&onlyReference=false
来源：牛客网

给定k个有序数组, 每个数组有个N个元素，找出一个最小的闭区间，使其包含每个数组中的至少一个元素。 
给定两个区间[a,b], [c,d]： 
如果 b-a < d-c，则认为[a, b]是更小的区间；
如果 b-a == d-c，且a < c，则认为[a, b]是更小的区间。

In [ ]:
k = int(input())
n = int(input())

ls = [[1] * n for i in range(k)]
for i in range(k): ls[i][:] = map(int,input().split())
    
result = [min(ls[0]), max(ls[0])]

pointer = [0] * k
while max(pointer)<= n-1:
    cur_ls = []
    for i in range(k):
        cur_ls.append(ls[i][pointer[i]])
    
    max_num, min_num = max(cur_ls), min(cur_ls)
    if max_num - min_num < result[1] - result[0]:
        result = [min_num, max_num]
        
    min_index = cur_ls.index(min_num)
    pointer[min_index] += 1
    
print(result[0], result[1])
        


In [200]:
# input
m,n=map(int,input().split())
img_ls = [[0]*n for i in range(m)]
for i in range(m):
    img_ls[i][:] = map(int,input().split())
    
img_ls

4 4 
100 234 342 234
123 213 343 3
23 34 45 34
21 34 213 34


[[100, 234, 342, 234], [123, 213, 343, 3], [23, 34, 45, 34], [21, 34, 213, 34]]

In [202]:
w,h=map(int,input().split())
kernel = [[0]*w for i in range(h)]
for i in range(h):
    kernel[i][:] = map(int,input().split())
    
kernel

5 5
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1
1 1 1 1 1


[[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]]

In [233]:
# padding 
padding_m = h//2
padding_n = w//2

padding_image = [[0]*(n+h-1) for i in range(m+w-1)]
padding_image

for i in range(m):
    padding_image[i+padding_m] = [0]*padding_n + img_ls[i] + [0]*padding_n
    
padding_image

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 100, 234, 342, 234, 0, 0],
 [0, 0, 123, 213, 343, 3, 0, 0],
 [0, 0, 23, 34, 45, 34, 0, 0],
 [0, 0, 21, 34, 213, 34, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0]]

In [234]:
for i in range(m):
    padding_image[i+padding_m] = img_ls[i][0:padding_m][::-1] + img_ls[i] + img_ls[i][-padding_m:][::-1]
    
    
for i in range(padding_m):
    for j in range(n):
        padding_image[i][j+padding_n] = padding_image[2*padding_m-1-i][j+padding_n]
        
for i in range(padding_m):
    for j in range(n):
        padding_image[padding_m+m+i][j+padding_n] = padding_image[padding_m+m-i-1][j+padding_n]
       
# corner 
for i in range(padding_m):
    for j in range(padding_n):
        padding_image[i][j] = padding_image[2*padding_m-1-i][2*padding_n-1-j]
        
        padding_image[i+padding_m+m][j] = padding_image[padding_m+m-i-1][2*padding_n-1-j]
        
        padding_image[i][padding_n+n+j] = padding_image[2*padding_m-1-i][padding_n+n-j-1]
        
        padding_image[i+padding_m+m][padding_n+n+j] = padding_image[padding_m+m-i-1][padding_n+n-j-1]
        
    
padding_image

[[213, 123, 123, 213, 343, 3, 3, 343],
 [234, 100, 100, 234, 342, 234, 234, 342],
 [234, 100, 100, 234, 342, 234, 234, 342],
 [213, 123, 123, 213, 343, 3, 3, 343],
 [34, 23, 23, 34, 45, 34, 34, 45],
 [34, 21, 21, 34, 213, 34, 34, 213],
 [34, 21, 21, 34, 213, 34, 34, 213],
 [34, 23, 23, 34, 45, 34, 34, 45]]

In [238]:
result_image = [[0]*n for i in range(m)]

for i in range(m):
    for j in range(n):
        x = i + padding_m
        y = j + padding_n
        mat = padding_image[x-padding_m:x+padding_m+1]
        v = 0
        for p in range(h):
            for q in range(w):
                v+= mat[p][q]*kernel[p][q]
        result_image[i][j] = int(v)
        
print(result_image)

[[4209, 4209, 4209, 4209], [3517, 3517, 3517, 3517], [2830, 2830, 2830, 2830], [1979, 1979, 1979, 1979]]


In [243]:
for i in result_image: 
    string = ''
    for j in i:
        string+= str(j) + ' '
    print(string[:-1])

4209 4209 4209 4209
3517 3517 3517 3517
2830 2830 2830 2830
1979 1979 1979 1979


In [251]:
import numpy as np

In [256]:
# input
# n,m=map(int,input().split())
# img_ls = [[0]*n for i in range(m)]
# for i in range(m):
#     img_ls[i][:] = map(int,input().split())
    
# w,h=map(int,input().split())
# kernel = [[0]*w for i in range(h)]
# for i in range(h):
#     kernel[i][:] = map(float,input().split())
    
# padding 
padding_m = h//2
padding_n = w//2

padding_image = [[0]*(n+h-1) for i in range(m+w-1)]

for i in range(m):
    padding_image[i+padding_m] = [0]*padding_n + img_ls[i] + [0]*padding_n
for i in range(m):    
    padding_image[i+padding_m] = img_ls[i][0:padding_m][::-1] + img_ls[i] + img_ls[i][-padding_m:][::-1]
    

for i in range(padding_m):
    for j in range(n):
        padding_image[i][j+padding_n] = padding_image[2*padding_m-1-i][j+padding_n]
        
        padding_image[padding_m+m+i][j+padding_n] = padding_image[padding_m+m-i-1][j+padding_n]
     
# corner 
for i in range(padding_m):
    for j in range(padding_n):
        padding_image[i][j] = padding_image[2*padding_m-1-i][2*padding_n-1-j]
        
        padding_image[i+padding_m+m][j] = padding_image[padding_m+m-i-1][2*padding_n-1-j]
        
        padding_image[i][padding_n+n+j] = padding_image[2*padding_m-1-i][padding_n+n-j-1]
        
        padding_image[i+padding_m+m][padding_n+n+j] = padding_image[padding_m+m-i-1][padding_n+n-j-1]
print(np.array(padding_image))        
result_image = [[0]*n for i in range(m)]

for i in range(m):
    for j in range(n):
        x = i + padding_m
        y = j + padding_n
        mat = padding_image[x-padding_m:x+padding_m+1]
        v = 0
        print(np.array(mat))    
        for p in range(h):
            for q in range(w):
                v+= mat[p][q]*kernel[p][q]
        result_image[i][j] = int(v)
        
for i in result_image: 
    string = ''
    for j in i:
        string+= str(j) + ' '
    print(string[:-1])

[[100 100 100 100 100]
 [100 100 100 100 100]
 [200 200 200 200 200]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]
[[100 100 100 100 100]
 [100 100 100 100 100]
 [200 200 200 200 200]]
[[100 100 100 100 100]
 [100 100 100 100 100]
 [200 200 200 200 200]]
[[100 100 100 100 100]
 [100 100 100 100 100]
 [200 200 200 200 200]]
[[100 100 100 100 100]
 [200 200 200 200 200]
 [  0   0   0   0   0]]
[[100 100 100 100 100]
 [200 200 200 200 200]
 [  0   0   0   0   0]]
[[100 100 100 100 100]
 [200 200 200 200 200]
 [  0   0   0   0   0]]
[[200 200 200 200 200]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]
[[200 200 200 200 200]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]
[[200 200 200 200 200]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]
130 130 130
110 110 110
60 60 60



3 3
100 100 100
200 200 200
0 0 0
3 3
0.09 0.12 0.09
0.12 0.16 0.12
0.09 0.12 0.09

In [1]:
n,k=map(int,input().split())

ls = [0]*n

ls = map(int,input().split())

4 4
3 3 3 3


In [22]:
ls = list(ls)

result = [1] * n

ls = [3]*4
print(result,ls)

[1, 1, 1, 1] [3, 3, 3, 3]


In [23]:
for i in range(n):
    for j in range(1,ls[i]+1):
        print(i, j)
        if i - j >= 0: result[i - j]+=1
        if i + j <= n-1: result[i + j]+=1

ans = 0
for i in result:
    if i >= k: ans+=1
        


    
print(ans)

0 1
0 2
0 3
1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3
4


In [24]:
n,k=map(int,input().split())

ls = [0]*n

ls[:] = map(int,input().split())
result = [1] * n

for i in range(n):
    for j in range(1,ls[i]+1):
        print(i, j)
        if i - j >= 0: result[i - j]+=1
        if i + j <= n-1: result[i + j]+=1

ans = 0
for i in result:
    if i >= k: ans+=1
        
print(ans)

4 4
3 3 3 3
0 1
0 2
0 3
1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3
4


In [26]:
n = int(input())

ls = [[1] * 2 for i in range(n)]
for i in range(n): ls[i][:] = map(int,input().split())
    

5
1 5
2 4
2 3
1 4
2 5


In [ ]:
5
1 5
2 4
2 3
1 4
2 5

In [43]:


ls_n = [ls[-1]]
ls_n

[[2, 5]]

In [47]:
cmp = ls[-1]

for i in range(n-2,-1,-1): 
    flag = True 
    if ls[i][0] >= cmp[0] and ls[i][1] <= cmp[1]:
        continue
    
    for num in ls_n:
        if ls[i][0] >= num[0] and ls[i][1] <= num[1]:
            flag = False
            break
    if flag: 
        ls_n.append(ls[i])
        if ls[i][0] <= cmp[0] and ls[i][1] >= num[1]:
            cmp = ls[i]
    print(ls[i], ls_n)

[1, 4] [[2, 5], [1, 4], [1, 5]]
[1, 5] [[2, 5], [1, 4], [1, 5]]


In [55]:
n = int(input())

lr = [[0 for i in range(2)] for j in range(n)]

for i in range(n):
    lr[i][0], lr[i][1] = map(int, input().split())

2
2 3
3 4


In [63]:
n = 5
lr = [[1,5],[2,4],[2,3],[1,4],[2,5]]

remove = 0
for i in range(n):
    left = lr[i][0]
    right = lr[i][1]
    for j in range(i+1, n):
        if left >= lr[j][0] and right <= lr[j][1]:
            remove += 1
            break
        
print(remove)

2


In [74]:
def match_parentheses(s):

    ls = []
    parentheses = "()[]{}"
    for i in range(len(s)):
        cur = s[i]

        if parentheses.find(cur) == -1:
            continue
        if cur in ['(', '[', '{']:
            ls.append(cur)
            continue
        if len(ls) == 0:
            return False

        p = ls.pop()
        if (p == '(' and cur == ')') or (p == '[' and cur == ']') or (p == '{' and cur == '}'):
            continue
        else:
            return False

    if len(ls) > 0:
        return False
    return True


if __name__ == '__main__':
#     s = input()
    s = "{abc}"
    result = match_parentheses(s)
    print(result)



True


In [ ]:
2.  寻找最长递增子序列
     input ：int  list  
     example: [1,3,5,2,4,6,7,8]  -> 6 
     return length

In [90]:
def LIS(B, d, n):
    left = right = mid = l = 1
    B[0] = d[0]   
    for i in range(1, n):
        left = 0
        right = l 
        while(left <= right):
            mid = (left + right) // 2
            if(B[mid] < d[i]):
                left = mid + 1
            else:
                right = mid - 1
        B[left] = d[i] 
        if(left > l) :
            l += 1
    return l
 
if '__name__ = __main__' :
    
    d = [1,3,5,2,4,6,7,8]
    B=[0]*len(d) 
    print(LIS(B, d, len(d)))

1


In [100]:
def lis(li):
    
    d = [1] * len(li)
    res = 1
    for i in range(len(li)):
        for j in range(i):
            if li[i] > li[j]:
                d[i] = max(d[i], d[j]+1)
            if d[i] > res: res = d[i]
    
    return res

li = [1,3,5,2,4,6,7,8]
print(lis(li))

6


In [64]:
k=input()
k

1.3


'1.3'

In [13]:
dic = {'a':1,'b':1,'c':1}

In [45]:
dic = []
val = []
for i in k:
    if i in dic:
        val[dic.index(i)] += 1
    else: 
        dic.append(i)
        val.append(1)
     



In [46]:
val[val.index(min(val))] -= 1
val[val.index(max(val))] += 1

result = 0
for i in val:
    result += i*i
print(result)

7


In [53]:
a = '121211'
a.find('.')

float(1.23)

1.23

In [59]:
def str2num(s):
    
    if s.find('.') == -1 or s.find('.') + 1 == len(s):
        return float(s)
    else:
        
        big = s[:s.find('.')]
        small = s[s.find('.')+1:]
        if small.find('.') == -1: return float(s)
        else:
        
            return float(s[:len(big)+small.find('.')+1])

In [84]:
n = 7
k = 3

result = ''
if k > n -1: print('-')
else:
    for i in range(n-k-1):
        result += 'B'
        

    result = result + 'A'
    
    for i in range(k):
        result += 'B'
        
    print(result)

BBBABBB


In [95]:
m,n=map(int,input().split())

ls = [0]*m

ls[:] = map(int,input().split())

5 4
1 1 2 3 3


In [96]:
dic = []
val = []
for i in ls:
    if i in dic:
        val[dic.index(i)] += 1
    else: 
        dic.append(i)
        val.append(1)
print(dic, val) 

[1, 2, 3] [2, 1, 2]


In [98]:
result = 4000


for i in range(len(dic)):
    left = n-val[i]
    if sum(val[:i]) >= left:
        current_result = 0
        point = i
        level = 1
        while left > 0:
            point -= 1
            if left >=val[point]:
                current_result += level * val[point]
                left = left - val[point]
                level += 1
            else: 
                current_result += level * left
                break
        
        if current_result < result:
            result = current_result
print(result)

3
